version: '3'

services:
  postgres:
    image: 'postgres:18'
    container_name: 'java-postgres'
    environment:
      - 'POSTGRES_USER=root'
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
      - 'POSTGRES_DB=defaultDB'
  
  app:
    build: ./
    container_name: 'java-app'
    ports:
    - 8080:8080
    links:
      - 'postgres:myDB'